games:
  BreakoutDeterministic-v4:
    n_frames: 4
    seed_value: 42
    initial_exploration: 1.0
    final_exploration: 0.1
    final_exploration_frame: 1000000
    size_memory: 1000000
    batch_size: 32
    gamma: 0.99
    tau: 0.005
    learning_rate: 0.0001
    num_episodes: 1000000
    new_agent: True
    agent_load_path: " "
    game_info_load_path: " "
    save_frequency: 500
    record_frequency: 500
    update_freq_target: 10000
