agent:
  n_frames: 4
  seed_value: 42
  initial_exploration: 1.0
  final_exploration: 0.1
  final_exploration_frame: 1000000
  size_memory: 1000000
  batch_size: 32
  gamma: 0.99
  tau: 0.005
  learning_rate: 0.0001

games:
  BreakoutDeterministic-v4:
    num_episodes: 5000
    new_agent: False
    agent_load_path: " "
    game_info_load_path: " "
    save_frequency: 500
    record_frequency: 500
    evaluation_frequency: 50 
    num_evaluation_runs: 20
    update_freq_target: 10000
    enable_starter_action: True
    starter_action: 1

  PongDeterministic-v4:
    num_episodes: 1000
    new_agent: False
    agent_load_path: "results/PongDeterministic-v4/agent/agent_episode_1000.pkl"
    game_info_load_path: "results/PongDeterministic-v4/game/game_info_1000.pkl"
    save_frequency: 250
    record_frequency: 250
    evaluation_frequency: 25
    num_evaluation_runs: 20
    update_freq_target: 10000
    enable_starter_action: True
    starter_action: 1

  MsPacmanDeterministic-v4:
    num_episodes: 1000
    new_agent: True
    agent_load_path: " "
    game_info_load_path: " "
    save_frequency: 500
    record_frequency: 500
    evaluation_frequency: 50 
    num_evaluation_runs: 20
    update_freq_target: 10000
    enable_starter_action: False
    starter_action: -1
